Adicionando imagens 2.7.1 e 3.1.0 como latest
zrpaplicacoes/docker-in-rails pull request #3
Opened 2021-12-30 14:34 UTC by MatheusGodinho

2021-12-30 14:55 UTC, pedrogryzinsky requested changes

2021-12-30 14:55 UTC, pedrogryzinsky commented on ruby:2.7.1-alpine.Dockerfile
> +FROM ruby:2.7.5-alpine
não deveria ser 2.7.1? (pelo menos da especificação do arquivo build)

2021-12-30 14:55 UTC, pedrogryzinsky commented on ruby:2.7.1-alpine.Dockerfile
> +    RUBY_VERSION=2.7.5 \
idem, ou arruma no build ou altera aqui, por favor

2021-12-30 14:59 UTC, MatheusGodinho commented on ruby:2.7.1-alpine.Dockerfile
> +FROM ruby:2.7.5-alpine
o correto é a 2.7.5 mesmo, corrigi onde referenciava.

2022-01-03 12:42 UTC, pedrogryzinsky approved these changes

2022-01-03 12:42 UTC, merged